tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "gh"
brew "git"
brew "git-secret"
brew "postgresql"
brew "tmux"
brew "tmuxinator"
brew "trash-cli"
brew "yarn"
brew "zsh"
cask 'alfred'
cask 'clipy'
cask 'docker'
cask 'google-chrome'
cask 'karabiner-elements'
cask 'rectangle'
cask 'slack'
cask "font-fira-code"
cask "font-source-code-pro"
